# Training defaults for autoregressive transformer
device_batch_size: 24
total_batch_size: 262144
max_steps: 10000
learning_rate: 6.0e-4
weight_decay: 0.1
grad_clip: 1.0
warmup_ratio: 0.0
warmdown_ratio: 0.2
final_lr_frac: 0.0
eval_every: 250
eval_batches: 20
sample_every: 1000
sample_tokens: 50
sample_temperature: 0.8
save_every: 2500
